# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ItsLit' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ItsLit
    pod 'swift-vibrant'
  target 'ItsLitTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ItsLitUITests' do
    # Pods for testing
  end

end
